project_name: harbor_tag
before:
  hooks:
    - go mod download
builds:
  - main: .
    binary: harbor_tag
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - format_overrides:
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
